### ISSUE TITLE
Test examples in CI

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#1052]
We should be testing https://github.com/libp2p/go-libp2p-examples in CI. That is, we need a CI job that:

1. Clones the above repo.
2. Checks out a "next" branch if it exists, otherwise master.
3. Replaces go-libp2p with the version of go-libp2p being tested.
4. Builds the examples.

The _next_ branch allows us to keep examples up-to-date with libp2p master. Of course, there's still a chicken/egg problem where we'd need to merge a failing PR to go-libp2p first before fixing the examples, but at least we'll have CI yelling at us until we _do_ fix the examples.

---

Alternatively, we could try to get this to run on release only. But that's a little trickier.

**Comment by marten-seemann** [comment]
cc @mvdan. This looks similar to your proposal in https://github.com/ipld/ipld/pull/92#issuecomment-759356290 to test everything with updated dependencies.

**Comment by mvdan** [comment]
Yep - if I was designing this, I'd instead set up a cron job on the CI of go-libp2p-examples. For example, test all the examples once per day with the latest versions of all dependencies, or just the latest version of go-libp2p.

Having the CI of go-libp2p fail when go-libp2p-examples falls behind seems conceptually a bit confusing, as it's go-libp2p-examples that should start failing.

**Comment by Stebalien** [comment]
I agree but nobody checks CI for the examples. The idea is to warn: hey, this is a breaking change, you need to go fix the examples.

**Comment by mvdan** [comment]
We briefly discussed this on this week's Go triage. Someone mentioned whether we need go-libp2p-examples to be a separate repository, and I agree. The downsides are clear:

* Harder to discover for end users
* Harder for CI to ensure that they keep working
* Harder for us to maintain more repositories

Issue trackers are being consolidated into this repository, so that's another plus to joining repos.

It is possible to add extra CI machinery to partially solve the CI problem, but that doesn't feel like the best solution unless we're determined to keep the repositories separate.

--

I propose to move the examples to this repository, under a directory like `examples/`. If any of the examples have dependencies that we don't want in the main module's `go.mod`, we can use nested modules. Some current examples [already do this](https://github.com/libp2p/go-libp2p-examples/blob/master/pubsub/chat/go.mod).

I see two options:

1) Make the entire `examples` directory a Go module, so they all share dependencies without affecting the main module.
2) Only make the specific examples with extra dependencies into nested modules, such as `examples/pubsub/chat`.

I lean towards option 1 for its simplicity, and to prevent altering the main module's dependencies unintentionally in the future - but I'm happy to defer to the maintainers here.

In either of the two options below, the example `go.mod` files would `replace` go-libp2p to point at the root module in the repository. This way, CI and users on a local checkout would automatically get the right version of go-libp2p.

@Stebalien thoughts? cc @aschmahmann @lidel @warpfork

**Comment by mvdan** [comment]
Also, as per @biglep, if we agree to do this we should keep this issue open until we've migrated all examples and archived or deleted the other repository.

It's also likely that a number of examples are broken with the latest go-libp2p, and need work. This is true even if we don't join the repositories.

**Comment by aschmahmann** [comment]
Versioning the entire examples directory seems reasonable to me.

It probably also makes sense to put replace directives to `..` as a hint to CI so we don't introduce breaking changes by accident. It may lead to some awkward incidents like a breaking change in  go-libp2p that needs to make it into pubsub requiring the examples to point at a branch on pubsub, however that should hopefully incentivize us to decrease the time of the awkward state and make sure the relevant dependency repos have approved PRs that are ready for merging before merging in a breaking change.

cc @raulk in case he has any opinions/historical context to share here.

**Comment by mvdan** [comment]
> It probably also makes sense to put replace directives

Indeed, that's what I meant above. The examples, when run from a git clone, would always use the go-libp2p version in the same git checkout.

> however that should hopefully incentivize us to decrease the time of the awkward state and make sure the relevant dependency repos have approved PRs that are ready for merging before merging in a breaking change.

I agree. The only other alternative is "the examples remain broken at times between stable releases", which I think is not something we want.

> Versioning the entire examples directory seems reasonable to me.

To be clear, we wouldn't have to version the examples with tags, and noone should be adding that examples module as a requirement to their go.mod, so I think we can largely ignore its version.

**Comment by Stebalien** [comment]
This sounds like a good approach.

**Comment by BigLep** [comment]
Closing since https://github.com/libp2p/go-libp2p/pull/1092 was completed
