### ISSUE TITLE
Project Flare / Hole Punching tracking issue

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1122]
### Circuit v2
* https://github.com/libp2p/go-libp2p-circuit/pull/125 implements the circuit v2 spec
     * It might need some work to reduce the attack surface.
* Remove v1 circuit relay on the server side. The client has a built-in fallback to v1, and PL will continue to run v1 relays for a while.
* Build logic (using autonat events) to start a v2 relay if the node is publicly accessible.

Tentative timeline: Get this ready for the [go-ipfs v0.10 release](https://github.com/ipfs/go-ipfs/issues/8176).

### Hole Punching
* QUIC support: https://github.com/libp2p/go-libp2p-quic-transport/pull/194
* libp2p support: https://github.com/libp2p/go-libp2p/pull/1057
    * reduce the number of retries to 3. Data shows that most connection attempts succeed after one or two attempts, and are unlikely to succeed with more attempts

Tentative timeline: We should defer enabling this until a critical mass of nodes have upgraded and are running v2 relays.

### AutoRelay

Once a critical mass of v2 relays has been deployed, rewrite the code to use v2 relays (reserve slots and refresh reservations).
The selection logic should be two-fold:
- Use the DHT and find the closest peers in KAD space, reserve to 2 (or 3) relays from those candidates. Detection of v2 relay support is easy, we can simply wait for identify and see if the node supports the v2 hop protocol.
- Provide an option to configure static v2 relays (without a default list! we want to stop running relays and be a point a centralization) for users who run their own relays.

**Comment by marten-seemann** [comment]
Moving to https://github.com/libp2p/go-libp2p/issues/1039.

**Comment by BigLep** [comment]
I'm reopening this because https://github.com/libp2p/go-libp2p/issues/1039 has been closed but we have more to do here before "Project Flare" is "done".  I believe having no open project flare issues causes confusion.  People think it's done, when there is more to do.

What does "done" mean?
The definition I have in my head is that it is good enough to be on by default in go-ipfs.  Things I'm aware of to get to that point:
1. Mechanism to automatic discovery of relay servers.
2. CI testing to ensure we don't introduce any regressions
3. Documentation items? (e.g., https://github.com/libp2p/docs/issues/110 , https://github.com/libp2p/go-libp2p/issues/1017)
4. Plumbing through / enabling in go-ipfs.

@marten-seemann : happy to discuss this more here or in #libp2p-dev.  I know my list above is likely incorrect.  I assume you'll update the issue description to describe what actually remains.

Thanks!

**Comment by marten-seemann** [comment]
I disagree.

> 1. Mechanism to automatic discovery of relay servers.

That's #1351.

> 2. CI testing to ensure we don't introduce any regressions

That could be a testground issue, but doesn't justify keeping this issue open in my opinion. We have a lot of stuff we want to test better, and it makes little sense to keep the original "implement the feature" issue open for all of them.

> 3. Documentation items? (e.g., https://github.com/libp2p/docs/issues/110 , https://github.com/libp2p/go-libp2p/issues/1017)

Looks like we already have issues for those. Why is that not good enough?
Besides, the second one has nothing to do with Flare.

> 4. Plumbing through / enabling in go-ipfs.

That should be an issue in go-ipfs, not in go-libp2p.

> I'm reopening this because https://github.com/libp2p/go-libp2p/issues/1039 has been closed but we have more to do here before "Project Flare" is "done".

This issue here was created erroneously, that's why it was closed *the same day*. If at all, #1039 should have been reopened, not this one.

**Comment by BigLep** [comment]
@marten-seemann : I'm game to work in any issue.  It sounds like #1039 is preferred.

I want to have a way to be clear that "hole punching in go-libp2p is done to a state that we recommend key consumers like go-ipfs and lotus enable it by default".   https://github.com/libp2p/go-libp2p/issues/1039 was closed before we hit that state, so I assumed it was denoting a different milestone.

I'll plan on commenting more in #1039.
