### ISSUE TITLE
interop: failing Docker build

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1670]
See https://github.com/libp2p/go-libp2p/runs/7748159717?check_suite_focus=true.

@laurentsenta, could you have a look please?

**Comment by laurentsenta** [comment]
Thanks for re-running it. Is that the first crash since we introduced Testground?

Network hiccup: there was an `EOF` when docker tried to pull `busybox:1.31.1-glibc` from the docker registry (that's the runtime image we use in the go runner). It's similar to another error I've seen where `go mod download` drops because of a hiccup.

I'll create a ticket in testground.

**Comment by marten-seemann** [comment]
Another timeout, this time during `go mod download`: https://github.com/libp2p/go-libp2p/runs/7835153567?check_suite_focus=true

**Comment by marten-seemann** [comment]
And another failure just now. This is starting to impact development velocity.

I've disabled the workflow manually. We'll reenable once changes have been made that will fix / reduce flakiness.

**Comment by marten-seemann** [comment]
We're now using the dockerized tests from the test-plans repo, so we won't need this any more.
