### ISSUE TITLE
Lint with golangci-lint

### ISSUE THREAD

**Issue by estensen** [libp2p/go-libp2p#1843]
Running [golangci-lint](https://github.com/golangci/golangci-lint) on my machine I find quite a few improvements. Would it be an idea to add the linter to CI and gradually remove warnings? I can add an Action for it.

**Comment by marten-seemann** [comment]
We’re using our Unified CI setup. Using golangci-lint was discussed and we decided against it.

**Comment by MarcoPolo** [comment]
I looked and I think I found these two references:

https://github.com/protocol/.github/issues/41#issuecomment-812623506

and

https://github.com/protocol/.github/issues/6#issuecomment-759220140 

it seems like we don’t want everything from golangci-lint since sometimes it can be annoying. And it’s may lag behind releases on the underlying linters.

**Comment by marten-seemann** [comment]
There’s also https://github.com/ipld/ipld/pull/92, which contains a lot of discussion. 

In addition to not being up to date, golangci-lint also sometimes breaks the underlying linters. See https://twitter.com/dominikhonnef/status/1530695446007521280 for an example.
