### ISSUE TITLE
quic: QUIC listener doesn't respect the QUIC version of the listen address

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1904]
```go
func TestListenOnlyOnOneVersion(t *testing.T) {
	t.Run("only one draft-29", func(t *testing.T) {
		h1, err := libp2p.New(
			libp2p.Transport(libp2pquic.NewTransport),
			libp2p.ListenAddrStrings(
				"/ip4/127.0.0.1/udp/12345/quic", // QUIC draft-29
			),
		)
		require.NoError(t, err)
		defer h1.Close()

		addrs := h1.Addrs()
		require.Len(t, addrs, 1)
		require.Equal(t, ma.P_QUIC, getQUICMultiaddrCode(addrs[0]))
	})
}
```

This test fails, as the listener is listening on both versions.

**Comment by marten-seemann** [comment]
I found this when adding an integration test for QUIC version support as part of #1905. The test above should be added as an integration test.
It probably makes the most sense to work on a fix for this on top of #1905.

**Comment by MarcoPolo** [comment]
I agree this is a bug. I think we can fix this in a patch release.

**Comment by MarcoPolo** [comment]
On more discussion. This shouldn't be a patch release because it will change the behavior of the public api

**Comment by MarcoPolo** [comment]
As I started fixing this I realized that I was writing special logic in the swarm to handle listeners returning multiple (possibly changing over time) multiaddrs. This felt error-prone and like a leaky abstraction. I'm thinking now that we shouldn't have `Listener`s return multiple multiaddrs. This leaks the implementation detail of us using the same listener for multiple multiaddrs to the rest of the stack. This problem is highlighted in this issue because we want the `Listener` to only return one multiaddr (quic-draft29) until we ask the transport to give us another listener for the other multiaddr (quic-v1).

I also think this is a similar problem to the quic conn-reuse across the quic transport and WebTransport. And in that case we didn't (and shouldn't) have the quic `Listener` also return the webtransport multiaddr.

Because this involves potentially undoing the breaking API change we made here: https://github.com/libp2p/go-libp2p/pull/1881 that isn't released yet this is blocking issue for this next release. If we aren't sure we want this breaking change, we should avoid it.
