### ISSUE TITLE
Migrate off github.com/gorilla/websocket

### ISSUE THREAD

**Issue by guseggert** [libp2p/go-libp2p#1970]
The github.com/gorilla/websocket module, [used for WebSocket support by go-libp2p](https://github.com/libp2p/go-libp2p/blob/82315917f76ca1e9e1c3aca3ad957080f0ac870c/go.mod#L13), was [recently archived](https://github.com/gorilla#gorilla-toolkit) and is no longer maintained. 

The only other serious option I can find is https://github.com/nhooyr/websocket, but it does not support HTTP/2. There is also an attempt to fork the Gorilla repos here: https://github.com/gorillaincubator. Or go-libp2p could maintain its own fork.

**Comment by marten-seemann** [comment]
Thank you for opening this issue @guseggert. This is annoying, but I can't really say that this comes as a surprise.

> Or go-libp2p could maintain its own fork.

Given our recent experience with maintaining our own forks of libraries, I'd really really like to avoid that.

> The only other serious option I can find is https://github.com/nhooyr/websocket, but it does not support HTTP/2. 

To be honest, I don't think we need to care a lot about HTTP/2. Our use is having a single WebSocket connection on top of one TCP connection, so we don't really benefit from HTTP/2's stream multiplexing. Given that we're only doing a single WebSocket Upgrade request, the savings due to HPACK should be minimal as well.

There's also https://pkg.go.dev/golang.org/x/net/websocket, but it claims to lack some features of Gorilla and nhooyr (without specifying which 🙄).

**Comment by guseggert** [comment]
I also found this, I haven't done a deep dive so I don't know how appropriate it is: https://github.com/lesismal/nbio
