### ISSUE TITLE
UDP Holepunching with QUICK for more compatiable NAT traversal 

### ISSUE THREAD

**Issue by TheRook** [libp2p/go-libp2p#2058]
The hole punching documentation stays that DCUtR is being used with TCP:
https://docs.libp2p.io/concepts/nat/hole-punching/

The DCUtR documentation says that it works best with UDP and reasonably well with TCP:
https://github.com/libp2p/specs/blob/master/relay/DCUtR.md

The go-libp2p implementation is not considering the differences in how edge network routers may react to a TCP vs UDP hole-punch:
https://github.com/libp2p/go-libp2p/blob/58c4cb85533c7803aee9d5b171351a34e694992e/p2p/protocol/holepunch/holepuncher.go#L88-L99

Ideally - go-libp2p would try the most efficient UDP based holepunch first.  Which is probably UPnP, because that is the "offical" protocol for doing this.  If UPnP fails, then try a QUICKconnect with a UDP holepunch to see if can be used to form connection.  If this more efficient UDP method fails, then try the current TCP holepunch - if that fails then look for a relay... and if that fails then the client is likely being filtered by their ISP or government.

**Comment by p-shahi** [comment]
Hi, thanks for creating this issue but I will close it since it's better topic for the discussion forum: discuss.libp2p.io

>  Ideally - go-libp2p would try the most efficient UDP based holepunch - so maybe using QUICK with a UDP to see if that accepts connections - if it fails then try the current TCP holepunch - if that fails then look for a relay.

This is an improvement we've identified. See: https://github.com/libp2p/go-libp2p/issues/1785

Also, the Probe Lab team recently ran a hole punching measurement campaign and results will be published soon: https://discuss.libp2p.io/t/call-for-participation-nat-hole-punching-measurement-campaign/1690
