### ISSUE TITLE
add a config option to allow all protocols via circuit v2

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#2079]
We should do this if we want to drop v1 support

**Comment by lidel** [comment]
I'd love to expose this ability in Kubo as opt-in option under [Swarm.RelayService](https://github.com/ipfs/kubo/blob/master/docs/config.md#swarmrelayservice). 

People loved the fact they could use regular Kubo as a static relay v1 for their web app (in controlled environments, when both service and  clients running on web pages were set up statically).  Bitswap over relayed connection "just worked".

Since we've removed v1 service, it is impossible to do bitswap over relayed connection, and people are forced to run a [separate daemon](https://github.com/libp2p/go-libp2p-relay-daemon) just for the relay feature, which is pretty bad UX for using IPFS in web apps. 

With this new config option, people will be able to deploy web apps that run bitswap over relay again :+1: 
cc @2color @thediscordian

**Comment by marten-seemann** [comment]
@lidel that’s not what this issue is about. I don’t plan adding an unlimited relay mode here. The transition to circuit v2 (which enabled decentralized hole punching) was only possible _because_ relays are imposing strict usage limits.

**Comment by lidel** [comment]
@marten-seemann ack, i think we are on the same page, we talk about additional option to allow all protocols. 
I meant that this new option,  together with existing ability to set limits very high, allows users to have a (more-or-less) drop-in replacement for v1.

**Comment by Winterhuman** [comment]
Would this feature be advertised as a multistream protocol component, like `/libp2p/circuit/relay/0.1.0/all-protocols` as an example? (probably not the best way of constructing this, but you get the idea)

Being able to discover which nodes provide this feature would be very useful, as I imagine nodes willing to enable this will be quite scarce overall

**Comment by marten-seemann** [comment]
We don't need a config option, we can just say that if the relay gives us infinite limits we don't apply any filter which protocols can be used.

In fact, that's what we're already doing: https://github.com/libp2p/go-libp2p/blob/b2f119901fd36ede716d1e49f5b7ac0de4713cf6/p2p/protocol/circuitv2/client/dial.go#L181-L186

I confirmed that this actually works. An unlimited v2 relay can be started using the `relay.WithLimit(nil)` option to `libp2p.EnableRelayService` option. We could consider introducing a more intuitive way of doing this.

Other than that, I believe this issue is fully resolved.
