### ISSUE TITLE
failed to start relay finder: relayFinder already running

### ISSUE THREAD

**Issue by Shawn-Huang-Tron** [libp2p/go-libp2p#2234]
I start a node in my local mac, and sometimes this error will show up:
`2023-01-04T11:42:33.113+0800 ERROR autorelay autorelay/autorelay.go:80 failed to start relay finder {"error": "relayFinder already running"}`

It sounds like that most time it appeared after my mac running a whole night , or I close my mac.

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/107823650/229011315-25271700-80a5-4d25-a2b1-b71a4865e6be.png">

I have seen your code, is it because that when network changed, libp2p try to start relayFinder again?
Should this error be ignored?

<details>
<summary>go-libp2p v0.24.2</summary>
<pre>

</pre>
</details>

**Comment by MarcoPolo** [comment]
we probably check if is already running and not try to start it again. Want to take a stab at fixing it?

**Comment by Shawn-Huang-Tron** [comment]
Hope to fix it . Thank you. Cause this error won't have any effect to functionity but people will get confused.

**Comment by marten-seemann** [comment]
I think @sukunrt already has a fix for this.

**Comment by sukunrt** [comment]
this will be fixed by https://github.com/libp2p/go-libp2p/pull/2225 and https://github.com/libp2p/go-libp2p/pull/2225

however those are PRs for separate issues so a separate PR for this should be fine. 
the approach I used is here: 
https://github.com/libp2p/go-libp2p/blob/b78104daa98c367a90389c4c691b5ca095509184/p2p/host/autorelay/autorelay.go#L87-L95

**Comment by marten-seemann** [comment]
@sukunrt Is this fixed now?

**Comment by sukunrt** [comment]
yeah this should be fixed now
