### ISSUE TITLE
Quick question about Ed25519 with the libp2p-host example 

### ISSUE THREAD

**Issue by ssikdar1** [libp2p/go-libp2p#227]
Looking at the example here: https://github.com/libp2p/go-libp2p/blob/master/examples/libp2p-host/host.go

	// Generate an identity keypair using go's cryptographic randomness source
	priv, pub, err := crypto.GenerateEd25519Key(rand.Reader)

and then later when creating the Peer ID: 

	// A peers ID is the hash of its public key
	pid, err := peer.IDFromPublicKey(pub)

However in the go docs for go-libp2p-peer

There is also a function to create a peer corresponding to Ed25519:
https://godoc.org/github.com/libp2p/go-libp2p-peer#IDFromEd25519PublicKey 

func IDFromEd25519PublicKey
func IDFromEd25519PublicKey(pk ic.PubKey) (ID, error)
IDFromEd25519PublicKey returns the Peer ID corresponding to Id25519 pk

Should the example use this function since its using crypto.GenerateEd25519Key to generate the public key?

Or do you you use IDFromEd25519PublicKey when you generate a priv, pub pair with a function different from crypto.GenerateEd25519Key(rand.Reader)?

Or does it not matter what you use?

**Comment by whyrusleeping** [comment]
We're currently working on this distinction. The `IDFromPublicKey` puts the public key in a tagged struct, hashes it, and sets the peer ID to that hash. `IDFrom Ed25519PublicKey` embeds the public key in the peer ID, so that if you have the nodes peer ID, you have their public key as well. For now, I would recommend using `IDFromPublicKey`. `IDFromEd25519PublicKey` is experimental and not yet fully supported.

cc @JustinDrake

**Comment by avive** [comment]
this was pretty confusing for me as well so thanks for the clarification.

**Comment by Stebalien** [comment]
https://github.com/libp2p/specs/blob/master/peer-ids/peer-ids.md
