### ISSUE TITLE
Autonat changes the status to private incorrectly

### ISSUE THREAD

**Issue by master255** [libp2p/go-libp2p#2602]
Libp2p and DHT gets a lot of connections with an error at startup time. Always. Because of this Autonat almost always switches to private mode and only after a few minutes to public.
I think it is necessary to delay before starting autonat. Now there is no delay at all. A few seconds after the start an error arrives and the host with a white ip address gets private status.
Because of this, after the start, for several minutes, no one can connect to this host through the Internet. 

In continuation of https://github.com/libp2p/go-libp2p/issues/2046

**Comment by marten-seemann** [comment]
1. This doesn’t have anything to do with #2046.
2. I haven’t observed this on my public nodes.

**Comment by master255** [comment]
1. You don't have any errors when passing the bootstrap period in the DHT?
2. I only use the TCP protocol. Maybe nodes that use Quic will cause errors.
3. What if someone were to purposely cause errors when connecting to the DHT? Attackers?

**Comment by marten-seemann** [comment]
This might happen because at the beginning AutoNAT is operating on a limited amount of data. It's usually resolved very quickly:
<img width="709" alt="image" src="https://github.com/libp2p/go-libp2p/assets/1478487/c1453389-65c3-4be2-8352-86bc4a0a1b3e">

I don't see any need to fix this. Also, we're working on AutoNAT v2, which will have a much more sophisticated logic.

**Comment by master255** [comment]
Yes. That's the problem I'm talking about. It can be solved with a timeout.
