### ISSUE TITLE
Ability to ban connections from a peer

### ISSUE THREAD

**Issue by jvsteiner** [libp2p/go-libp2p#274]
While it's possible to disconnect a peer using `host.Network().ClosePeer(pid)`, currently it doesnt seem possible to prevent them from reconnecting.  In some cases this might be desireable - my use case is a pubsub use case, and I would use it to ban peers who send invalid messages to topics I am interested in. I understand that it's possible to _filter_ IP addresses, however, these could change.  

`go-floodsub` recently added the ability to Validate a message topic, and the API used to validate messages might be suitable for providing a banning mechanism to refuse connections from peers who are known to behave badly.  This way, developers could control the details of their own banning mechanisms.

**Comment by Stebalien** [comment]
Note: It's currently possible to just make new peer IDs so this isn't a perfect solution. However, we can improve that situation in the future. Furthermore, a way to ban (or explicitly backoff) certain peers will help when peers aren't necessarily malicious, just faulty.

**Comment by prestonvanloon** [comment]
We are interested in this functionality for Prysmatic Labs. 

Our specific use case is that if we discover a peer that is on a different blockchain, we wouldn't want to redial that peer in the future. 

Example workflow:
- Peer with newly discovered peer for the first time
- Negotiate blockchain information
- Disconnect & ban peer with disagreeable information
- Next DHT query, we may see the peer again, but we do not attempt to dial this peer because we already know they are not desirable.

**Comment by Stebalien** [comment]
@prestonvanloon are you trying to split your DHTs? If you should change your DHT's protocol name. Banning peers like that will slowly break _all_ DHT queries for you.

If you're trying to find peers participating in your blockchain, try https://github.com/libp2p/go-libp2p-discovery/. You can then tag any peers in your blockchain with a high value using the connection manager and let the connection manager prune other connections as necessary.

**Comment by prestonvanloon** [comment]
Why does it slowly break all DHT queries?

**Comment by Stebalien** [comment]
Because you'll slowly ban most of the DHT. DHT queries are recursive:

1. You query the peers closest to some target key.
2. These peers either return (a) the target value or (b) peers closer to the target key (in which case you go back to step 1).

As you slowly ban the entire DHT, you'll ban all peers in (2.b) and none of your queries will make progress.

**Comment by Stebalien** [comment]
There is now a "connection gater" interface to accomplish this. You can filter both inbound and outbound connections with callbacks.
