### ISSUE TITLE
Can we create tcp connection pool easily using libp2p?

### ISSUE THREAD

**Issue by yyh1102** [libp2p/go-libp2p#288]
I know that `stream` is running over a single connection and can be multiplexed, but is there any way to create tcp connection pool using libp2p, and each connection in pool can run multiple streams?

**Comment by Stebalien** [comment]
To the same endpoint? That's generally *not* a good idea (unless you have multiple links) as TCP congestion control works best with one connection.

**Comment by yyh1102** [comment]
OK, i got this. Thank you for your replying.
But if i have to do that, are there any elegant ways? 
I've found an api `*BasicHost.DialPeer` to establish a connection. In this way i don't have to create and operate a pool by myself and can just reuse `*Network.ConnsToPeer` to get the pool of connections.

**Comment by Stebalien** [comment]
While you can see all connections open to a given peer, we'll only ever open multiple connections if both sides dial each other at the same time. We don't expose any way to create additional connections.

So we don't try to solve the wrong problem, what's your end goal? That is, why do you *need* a connection pool?

**Comment by yyh1102** [comment]
In my case, an endpoint exchanges multiple packages continuously with the remote end point over tcp, and we care about the efficiency measured by `pps`(packages per second) or something like that. Cause the tcp connection may crash for the unknown reasons, the system have to wait for tcp reconnecting ( three handshakes and keys negotiation). So i think it's a better way to build several connections at first, and enforce the performance of message communication.
Maybe there are some misunderstanding on the tcp connection or libp2p, and i'll appreciate it if you can tell~Thanks~

**Comment by Stebalien** [comment]
So, there are two things that can go wrong with a TCP connection:

1. Some packets can be dropped. This can stall a connection for a few round trips. Unfortunately, simply switching to a new connection won't help much here because unless you're willing to use two connections in parallel. One *could* do that but that's often a bad idea: you'll see behaviour similar to a two lane highway merging into a one-lane highway.
2. Some middlebox/ISP can send an RST packet. Have a friendly chat with your ISP.

Really, what we want here is session resumption (but we don't support that yet).

---

We're also working on integrating a protocol called QUIC. This will help with problem (1) because dropping a packet on one stream won't block data transfer on the others. It should help with problem (2) because QUIC reset packets are authenticated. However, this may take a while to get fully merged.

**Comment by yyh1102** [comment]
As you said, maybe i can build several connections at first, and distribute packages over these connections in parallel. This can improve the performance of transfering in a sense.
Thank for your replying!  And i'm looking forward to QUIC protocol merged in libp2p!

**Comment by marten-seemann** [comment]
Closing, since we've had QUIC support for quite a while.
