### ISSUE TITLE
Export closeableBasicHost and closeableRoutedHost

### ISSUE THREAD

**Issue by dennis-tra** [libp2p/go-libp2p#3015]
In some of our tooling I want to have access to the IDService. What I've done until recently is:

- get a host via `libp2p.New`
- type cast/assert it to a `*basichost.BasicHost`
- access the exported `.IDService()` method

A few months ago the host that `libp2p.New` returns is wrapped inside a `closeableBasicHost`. Since this type isn't exported I cannot do the above anymore.

Maybe there's a more elegant way to do what I want?

If not, would you have any objections to export that type? Increasing the API surface needs to be carefully considered so I'd totally understand if you have reservations. However, if it's ok from your side, I'm happy to do the tiny change.

**Comment by aschmahmann** [comment]
Related issue https://github.com/libp2p/go-libp2p/issues/2809

**Comment by MarcoPolo** [comment]
I think using Fx's options for this is cleaner than having to type check against specific type or having to expose a new getter method in the Interface.

This PR would let you do it: https://github.com/libp2p/go-libp2p/pull/2956. Here's a test that demonstrates it: https://github.com/libp2p/go-libp2p/pull/2956/files#diff-f7fee66901d4e06c6566ce6e9859d0b89364d4ba13ad9edd24534bfecdb443cbR54

This would work even if the host itself doesn't use the ID service. As long as something is providing it in the dependency graph.

I'm leaning towards merging that PR so we can start using it since it has already come up a couple of times.

**Comment by MarcoPolo** [comment]
You'll be able to get the ID service in the next release. Refer to this test for an example: https://github.com/libp2p/go-libp2p/blob/c4c3a34545aab54b5b825a7adbd6a3db2c680afa/fx_options_test.go#L50-L60

**Comment by dennis-tra** [comment]
Thanks everyone, and apologies for not searching for a related issue! Great that 0.37 is already released!
