### ISSUE TITLE
 How to achieve punching behind nat or firewall, Is there an example?

### ISSUE THREAD

**Issue by jiangsuwwj1** [libp2p/go-libp2p#312]
I want to achieve p2p communication through libp2p, and these two are in the private network, how should I do?

**Comment by agahEbrahimi** [comment]
Does the bootstrap example work correctly?

**Comment by agahEbrahimi** [comment]
@upperwal No, I'm referring to the peer discovery and not the port mapping. Sorry I phrased my question incorrectly.

**Comment by upperwal** [comment]
I believe it should work. Just try it. More info on compiling [here](https://github.com/jvsteiner/go-libp2p/tree/db49891d9b93818d9f06276b3a064b8fba6f77d8/examples/routed-echo)

**Comment by agahEbrahimi** [comment]
Is it just on a local network or does it work across routers (over internet) too?

**Comment by upperwal** [comment]
Yes, you can run it across networks (the internet) **easily** if your system has a public IP address and **not so easily** if they are behind NAT (have a private IP address). 

Incase of public IP's you just have to replace ```127.*.*.*``` or ```192.168.*.*``` with your public IP's.

Incase of a NAT (private IP's), process to establish connection will be complicated (don't worry everything is taken care within libp2p). Libp2p will use NAT port mapping (the thing I was talking about earlier) to convert ```LOCAL_IP:LOCAL_PORT``` to ```PUBLIC_IP:PUBLIC_PORT```

You need to know what ```PUBLIC_IP:PUBLIC_PORT``` mapping is done by NAT Manager. For example using a bootstrap node to store all the incoming nodes info and giving it to the nodes requesting for it (DHT).

**Comment by agahEbrahimi** [comment]
Ah, so I just change the IPs in the Go code to their respective public IPs and they would be able to find each (after the Nat Port mapping process which you were talking about)? but wouldn't they still have to have the session hash? 
`> ./routed-echo -l 10000
2018/02/19 12:22:32 I can be reached at:
2018/02/19 12:22:32 /ip4/127.0.0.1/tcp/10000/ipfs/QmfRY4vuKpU2tApACrbmYFn9xoeNzMQhLXg7nKnyvnzHeL
2018/02/19 12:22:32 /ip4/192.168.1.203/tcp/10000/ipfs/QmfRY4vuKpU2tApACrbmYFn9xoeNzMQhLXg7nKnyvnzHeL
2018/02/19 12:22:32 Now run "./routed-echo -l 10001 -d QmfRY4vuKpU2tApACrbmYFn9xoeNzMQhLXg7nKnyvnzHeL" on a different terminal
2018/02/19 12:22:32 listening for connections`
on the fourth line it says that the other has to run the Go code using a hash paramater that is given by the first node, but if the first node isn't connected to the second node, then how would that hash get passed? If we assume that the second node is new to the network they would have to know that session hash, which they don't because they aren't connected.

**Comment by upperwal** [comment]
When you ran ```./routed-echo -l 10000``` info about this node is stored on the DHT (Distributed Hash Table) and will be used to map ```node_hash``` to ```multiaddr```.

On executing ```./routed-echo -l 10001 -d QmfRY4vuKpU2tApACrbmYFn9xoeNzMQhLXg7nKnyvnzHeL```, ```multiaddr``` corresponding to this hash is retrieved from the DHT which can be used to open a stream with this node.

**Comment by agahEbrahimi** [comment]
I get that part but if the person running the ./routed-echo -l 10001 -d QmfRY4vuKpU2tApACrbmYFn9xoeNzMQhLXg7nKnyvnzHeL has never initiated contact with the other node how does it get access to this address "QmfRY4vuKpU2tApACrbmYFn9xoeNzMQhLXg7nKnyvnzHeL"?

**Comment by Stebalien** [comment]
@jiangsuwwj1 there's a bootstrapping example here: https://github.com/libp2p/go-libp2p/pull/278

**Comment by jiangsuwwj1** [comment]
@Stebalien Thank you very much, I will try later.
