### ISSUE TITLE
Speeding up DHT and Discovery

### ISSUE THREAD

**Issue by agahEbrahimi** [libp2p/go-libp2p#318]
Hello, 

I was trying to recreate [this](https://gist.github.com/whyrusleeping/169a28cffe1aedd4419d80aa62d361aa) demo for a simple chat application and saw that for the discovery it's using Bootstrap and DHT, and it takes a while for it to find all the peers. What I was wondering was, can you save the data that was recalled before and then retrieve it again so that you wouldn't have to go through that long process each time you want to run the app.

Thank you

**Comment by florianlenz** [comment]
What exactly takes too long? The bootstrapping or finding your co peer's? `What I was wondering was, can you save the data that was recalled before and then retrieve it again so that you wouldn't have to go through that long process each time you want to run the app.` I don't know what data exactly you are referring to, but you can save peer's in the peerstore: https://github.com/libp2p/go-libp2p-peerstore. BUT keep in mind that peer's go offline and online and might change addresses. So I don't know if it fit's your use case :)

**Comment by agahEbrahimi** [comment]
Sorry I responded so late. Peerstore was what I was looking for, and I found it about an hour after I posted this comment. Thank you anyway.
