### ISSUE TITLE
NAT Traversal in chat example

### ISSUE THREAD

**Issue by Harrywang55666** [libp2p/go-libp2p#375]
Hi, I'm new to libp2p
https://github.com/libp2p/go-libp2p/tree/master/examples/chat
This example shows peer A (A behind NAT) connect peer B (B has public IP), but B couldn't connect A. I don't think it is a typical P2P example. How could a peer to connect a peer which behinds NAT or firewall, give us an example please.

**Comment by Stebalien** [comment]
The almost-always works answer is:

1. Enable the circuit relay protocol (the `EnableRelay` option).
2. Pick some set of nodes that you want to use as relays.
3. Advertise these addresses using the `AddrsFactory` option.

Eventually, we'd like to automate the second two pieces but that means we'd need an automated way to find and pick good relays.

---

Canned NAT traversal explanation: We have three nat-traversal solutions at the moment.

**UPnP/NATPortMap**

When NAT traversal is enabled (in go-libp2p, pass the `NATPortMap()` option to the libp2p constructor), libp2p will use UPnP and NATPortMap to ask the NAT's router to open and forward a port for libp2p. If your router supports either UPnP or NATPortMap, this is by far the best option.

**STUN/hole-punching**

LibP2P has it's own version of the "STUN" protocol using peer-routing, external address discovery, and reuseport. LibP2P:

1. Uses the same source port for both dialing and listening (reuseport).
2. Receives observed address information from all connected peers (external address discovery).
3. Publishes these addresses to the network (peer routing).

* On *some* NATs, the first feature allows us to accept new inbound connections on the source port used by the *router* (the "mapped" source port).
* The second feature allows us to discover this mapped source port and our external address.
* The third feature allows us to *tell* the network about this external address.

**TURN-like protocol**

Finally, we have a TURN like protocol called p2p-circuit. This protocol allows libp2p nodes to "proxy" through other p2p nodes. Unfortunately, neither go-libp2p nor js-libp2p *announce* p2p-circuit addresses at the moment (by default). This means that it doesn't just automagically bypass NATs (yet).

The next steps here are to:

1. Have all nodes behind NATs connect to "hub" nodes that volunteer to act as p2p-circuit relays.
2. Announce to the network that we're accepting relay connections from these nodes.

**Corporate Firewalls**

While technically a different issue, this still falls under the category of working around meddlesome middle boxes.

Currently, we don't have any good ways to work around corporate firewalls. However, we have an issue (https://github.com/ipfs/go-ipfs/issues/5251) to enable the websocket listener *by default* on go-ipfs which will help significantly because this transport supports HTTP proxies out of the box. Note: This won't be *fully* solved until p2p-circuit becomes fully automatic as proxy support only allows us to dial, not listen.

**Comment by Harrywang55666** [comment]
How could I build circuit relay peer?

**Comment by Stebalien** [comment]
Use the `EnableRelay(OptActive, OptHop)` to allow peers to relay through the node.

**Comment by Harrywang55666** [comment]
If A and B are behind two different NAT, that means I need a third peer C act like a circuit relay which has public ip to help A connect B or B connect A?

**Comment by Stebalien** [comment]
Yes. However, most nodes will allow relaying between already connected nodes by default. That is, if you have both A and B connect to *any* peer C, you should be able to connect A to B by calling:

```go
myHost.Connect(context.Background(), pstore.PeerInfo{ID: peerC, Addrs: []{ma.StringCast("/ipfs/peerIdC/p2p-circuit/ipfs/peerIdB")})
```

(exact syntax may be incorrect, I haven't tested it.

**Comment by Harrywang55666** [comment]
If A and B was connected by work of relay C in the case above, the transport of data between A and B is directly or forward by C?

**Comment by Stebalien** [comment]
It would be forwarded. Connecting two nodes behind full NATs without port forwarding is tricky at best and isn't always possible.

**Comment by Harrywang55666** [comment]
Emmm, could you show me NAT traversal  using hole-punching please.

**Comment by upperwal** [comment]
@Harrywang55666 

Maybe this example ([Chat w/ Bootstrapping](https://gist.github.com/upperwal/38cd0c98e4a6b34c061db0ff26def9b9#file-libp2p_chat_bootstrapping-md)) could help. This might be broken (written it long time back). It only uses hole punching (which is enabled by default so you won't see anything related to hole punching in the example) for NAT and DHT to find new peers.

Try it and let me know if it still works.

@Stebalien If you think this is a good example for p2p chat, I can polish it and open a PR.

**Comment by Harrywang55666** [comment]
Your code would not be build successfully because the "github.com/libp2p/go-libp2p package" imports "gx/ipfs/Qmb8T6YBBsjYsVGfrihQLfCJveczZnneSBqBKkYEBWDjge/go-libp2p-host" but "github.com/libp2p/go-libp2p-kad-dht" imports "github.com/libp2p/go-libp2p-host", so host created by libp2p.New returns "gx/ipfs/Qmb8T6YBBsjYsVGfrihQLfCJveczZnneSBqBKkYEBWDjge/go-libp2p-host".Host, but dht.NewDHTClient wants "github.com/libp2p/go-libp2p-host".Host, and this is not the only building error. What should I do???
Thank you very much

**Comment by Harrywang55666** [comment]
Okay, I solved, just rewind by running make publish....

**Comment by Harrywang55666** [comment]
I have changed the lines where create a host:
sourceMultiAddr, _ := multiaddr.NewMultiaddr("/ip4/0.0.0.0/tcp/4001")
host, err := libp2p.New(ctx, libp2p.Defaults, libp2p.ListenAddrs(sourceMultiAddr))
if err != nil {
	panic(err)
}
then I ran the program in three different terminals, and each terminal showed me a message "Found 1 peers!", which means these three terminals couldn't find out each other.
Did I do something wrong?

**Comment by Stebalien** [comment]
You're reusing the same address for each peer. That's not going to work well.

**Comment by Harrywang55666** [comment]
I change to:
host, err := libp2p.New(ctx, libp2p.Defaults, libp2p.ListenAddrStrings("/ip4/0.0.0.0/tcp/0"))
but and it still doesn't work. Each peer could not discover each other as well.
![image](https://user-images.githubusercontent.com/11702572/43181561-724d53a8-9010-11e8-9c36-5474a0e20a94.png)
![image](https://user-images.githubusercontent.com/11702572/43181566-7b357810-9010-11e8-8f31-64d5d9165619.png)
![image](https://user-images.githubusercontent.com/11702572/43181576-8734047e-9010-11e8-89e7-65dc6e148ba5.png)

**Comment by Harrywang55666** [comment]
I did some debug work. I found an "proto: invalid UTF-8 string" error returned by dht.sendRequest from *IpfsDHT.findProvidersSingle at dht.go:313 when main function was calling dht.FindProviders. But the error was not returned to the main function.
The picture below shows the call stack and debug variables:
![image](https://user-images.githubusercontent.com/11702572/43190319-554b39a8-902b-11e8-9530-e315b2a5a24c.png)
Does it mean dht client peer could not read response from bootstrap peer, so that causes dht.FindProviders would always returns self peer?

**Comment by upperwal** [comment]
@Harrywang55666 
Try changing the rendezvous string in the following line
```go
c, _ := cid.NewPrefixV1(cid.Raw, multihash.SHA2_256).Sum([]byte("meet me here"))
```

![screen shot 2018-07-25 at 3 28 08 pm](https://user-images.githubusercontent.com/5246435/43194349-c426dbea-901f-11e8-8cb3-493078be528b.png)

**Comment by Harrywang55666** [comment]
@upperwal So sad. It still does't work🙄
I still doubt that *messageSender.SendRequest error cause the failure...

**Comment by upperwal** [comment]
@Harrywang55666 are you using the latest version of libp2p and its dependencies?

**Comment by Harrywang55666** [comment]
just go get without using gx
should i try to run go get -u github.com/libp2p/go-libp2p/...

**Comment by upperwal** [comment]
@Harrywang55666 yeah try that and remove libp2p folder entirely including multiaddr folder from <GO_ROOT>/src/github.com/...

Basically install everything (even deps) from scratch w/o gx

**Comment by Harrywang55666** [comment]
@upperwal I ran go get -u -d github.com/libp2p/... but still doesn't work...

**Comment by upperwal** [comment]
github.com/multiaddr

**Comment by Harrywang55666** [comment]
Then I run go get -u -d github.com/llibp2p/go-libp2p/... ?

**Comment by upperwal** [comment]
yes and
go get -d github.com/libp2p/go-libp2p-kad-dht/...
go get -d github.com/libp2p/go-floodsub/...

You may also need to remove github.com/multiformats and install them again

go get -d github.com/multiformats/go-multistream/...
go get -d github.com/multiformats/go-multiaddr-dns/...
go get -d github.com/multiformats/go-multiaddr-net/...

**Comment by Harrywang55666** [comment]
@upperwal It's too late in China, I will try them tomorrow morning. Good night!

**Comment by upperwal** [comment]
Sure. Goodnight.

**Comment by Harrywang55666** [comment]
@Stebalien @upperwal I don't wanna bother you but I really need help guys...🙄

**Comment by upperwal** [comment]
Try updating go as well.

**Comment by Harrywang55666** [comment]
@upperwal my go version is 1.10. Should I try to re-generate pb files?

**Comment by Harrywang55666** [comment]
@upperwal The package uses github.com/gogo/protobuf instead of github.com/golang/protobuf

**Comment by Harrywang55666** [comment]
@upperwal I have updated my go to 1.10.3 (darwin/amd64), and the error is not disappeared either. Now I doubt that github.com/gogo/protobuf package version is too latest to cause this error...

**Comment by Harrywang55666** [comment]
@upperwal Maybe you could try to update your protobuf package to check it out.

**Comment by Harrywang55666** [comment]
@upperwal Finally！！！！！I ran "gx install" to get the correct version of gogo/protobuf. Then I replaced the import from "github.com/gogo/protobuf/..." to "gx/ipfs/blablablablabla/gogo-protobuf/..."  MANUALLY. Then everything went well. But it takes bits of time to run Provide and FindProviders and NewStream. Maybe it is because of the network. Anyway, My terminals can chat now! Thanks for your guidance and patient @Stebalien @upperwal 
![image](https://user-images.githubusercontent.com/11702572/43253047-969be3b4-90f6-11e8-893d-34a2566cc3ce.png)
![image](https://user-images.githubusercontent.com/11702572/43253060-9ba37246-90f6-11e8-8704-6fd0ff3eece4.png)
![Uploading image.png…]()

**Comment by upperwal** [comment]
@Harrywang55666 congrats 👍  maybe you can try updating github.com/gogo/protobuf/ and then compile w/o gx

or

Add a new example (your code) to go-libp2p/examples/... and do ```make``` followed by ```make deps```

This way you don't have to manually replace anything. Keeping that aside, hack whatever is running for now 😄

**Comment by Harrywang55666** [comment]
@upperwal Sorry to bother you again. I tested with peers behind different NATs, but it didn't work. Did that mean peer had tried to do hole punching(STUN) but failed , or the peer just tried to connect with  peers' internal addresses directly but failed.

**Comment by upperwal** [comment]
@Harrywang55666 STUN may not work in all situations (look [here](https://stackoverflow.com/questions/23655243/nat-traversal-probability-of-success-using-stun)). Maybe you can try NAT port mapping by enabling it in libp2p. Here is how you would do it:
```go
host, err := libp2p.New(
	context.Background(),
	libp2p.NATPortMap(),
)
```

```NATPortMap()``` will attempt to open a port in your network's firewall using UPnP. ([docs](https://godoc.org/github.com/libp2p/go-libp2p#NATPortMap)). Try this and see if it works.

**Comment by upperwal** [comment]
@Harrywang55666 you might be interested in libp2p/go-libp2p-kad-dht#177 issue.

**Comment by Harrywang55666** [comment]
I have a log `DiscoverGateway error: no NAT found` with using `NATPortMap `

**Comment by upperwal** [comment]
@Harrywang55666 UPnP is not supported or enabled in our router.

**Comment by Harrywang55666** [comment]
I will get `no NAT found ` if my router does not support UPnP?
I wonder whether method `host.Connect` would try UPnP and STUN and p2p-circuit util the connection established.

**Comment by Harrywang55666** [comment]
@upperwal I will get no NAT found if my router does not support UPnP?
I wonder whether method host.Connect would try UPnP and STUN and p2p-circuit util the connection established.

**Comment by upperwal** [comment]
> I will get no NAT found if my router does not support UPnP?

Yes, even if it is disabled. (As far as my knowledge goes)

> I wonder whether method host.Connect would try UPnP and STUN and p2p-circuit util the connection established.

STUN is enabled by default. UPnP is enabled when you use ```libp2p.NATPortMap()``` and p2p-circuit is be enabled as described by Stebalien above. All of them are used to establish a connection. UPnP and STUN can be used together. p2p-circuit is different because it uses a proxy peer. If you enable all three, libp2p will try to establish a connection using one or all.

**Comment by Harrywang55666** [comment]
@upperwal any p2p-circuit examples or code block?

**Comment by upperwal** [comment]
Sorry, I am not aware of any. 

[transport_test.go](https://github.com/libp2p/go-libp2p-circuit/blob/master/transport_test.go) and [relay_test.go](https://github.com/libp2p/go-libp2p-circuit/blob/master/relay_test.go) can help.

**Comment by Stebalien** [comment]
Note: we have a very primitive STUN-like protocol that only works for some NATs. Also unfortunately, we don't advertise p2p-circuit addresses by default. See: https://github.com/ipfs/go-ipfs/issues/4992

As for the gogo protobuf issue... yeah, we'll have to fix that.

**Comment by Harrywang55666** [comment]
@Stebalien @upperwal I'm curious about that which peer performs as STUN server in this [case](https://gist.github.com/upperwal/38cd0c98e4a6b34c061db0ff26def9b9#file-libp2p_chat_bootstrapping-md). Is bootstrap peer? I guess...

**Comment by Harrywang55666** [comment]
@myleshorton ICE uses STUN and TURN to traverse NATs.

**Comment by myleshorton** [comment]
> @myleshorton ICE uses STUN and TURN to traverse NATs.

Yup exactly. STUN is basically just a protocol for learning the IP and port the remote endpoint sees.

**Comment by Harrywang55666** [comment]
@upperwal I read the [Peer-to-Peer Communication Across Network Address Translators](http://www.brynosaurus.com/pub/net/p2pnat/) these couple of days. And I looked for **_hole punching_** process in libp2p's code, but I couldn't find out. And I found this in github.com/libp2p/go-addr-util/addr.go:
![image](https://user-images.githubusercontent.com/11702572/43821819-bdd7f2bc-9b1c-11e8-9e04-28afa38eb908.png)
What does that mean? BTW, I still can't find the usage of `CheckNATWarning`

**Comment by Stebalien** [comment]
We're doing *basic* hole punching that only works on some NATs. Full hole punching requires simultaneous connect, which we don't do (yet). We're just establishing all outbound connections using the same source port and then learning how the NAT maps this port to an external port. Some NATs (I've been told) will allow inbound connections on the same port (and will maintain the mapping for these connections).

**Comment by leslie-wang** [comment]
is there any well known p2p-circuit relay nodes, which I can use to test?

**Comment by Stebalien** [comment]
Not that I know of, yet.

**Comment by leslie-wang** [comment]
Based on above discussion and my experiements, seems like example chat-with-rendezvous can work cross 2 peers behind NAT. But when I try this scenario, seems like it can not work cross NAT. Can you please help verify?
 - Peer A is behind NAT, connect to bootstrap nodes with specified private / public key. The process is similiar as th libp2p-host example. 
```
priv, _, _ := crypto.GenerateEd25519Key(rand.Reader)
host, _ := libp2p.New(ctx,libp2p.Identity(priv))
for _, peerAddr := range bootstrapNodes {
	addr, _ := iaddr.ParseString(peerAddr)
	peerinfo, _ := pstore.InfoFromP2pAddr(addr.Multiaddr())
	node.host.Connect(ctx, *peerinfo);
}
```
- Peer B is also behind NAT, and connect to same sets of bootstrapNodes, then try to find the Peer using its PeerAPID as below. Seems like it fail. 
```
priv, _, _ := crypto.GenerateEd25519Key(rand.Reader)
host, _ := libp2p.New(ctx,libp2p.Identity(priv))
for _, peerAddr := range bootstrapNodes {
	addr, _ := iaddr.ParseString(peerAddr)
	peerinfo, _ := pstore.InfoFromP2pAddr(addr.Multiaddr())
	node.host.Connect(ctx, *peerinfo);
}
kadDHT, _ = dht.New(ctx, host)
pi, err := kadDHT.FindPeer(ctx, PeerAPID)
```
Is it because PeerA doesn't broadcast its address? I can not find any APIs in `go-libp2p-kad-dht`

**Comment by upperwal** [comment]
@leslie-wang Your code won't work because you need to create a new ```dht``` instance before connecting to any peer. Let me explain why.

```dht``` use notifications like ```Connected``` (when a new connection to a peer is established), ```Disconnected``` (when your peer disconnect from a peer), ```OpenedStream``` (even ever a new stream is opened) etc. [go-libp2p-kad-dht/notif.go](https://github.com/libp2p/go-libp2p-kad-dht/blob/master/notif.go)

What you need is:
```go
host, _ := libp2p.New(...opts)
kadDHT, _ = dht.New(ctx, host)
host.Connect(ctx, *peerinfo);
```

```dht.New``` will register notifications on this host. [See this](https://github.com/libp2p/go-libp2p-kad-dht/blob/d70e92744b101ddf9ed93066a54ce128fa53aaa8/dht.go#L77-L78)

So, now you can call ```Connect``` and as soon as a new connection is established ```dht``` will get the notification ```Connected``` and the new peer is added to dht's peerstore.

> node.host.Connect(ctx, *peerinfo);

What is this node? Is this a typo or am I missing something?

**Comment by leslie-wang** [comment]
@upperwal thanks for the reply. The code snippet is from https://github.com/leslie-wang/libp2p-ftp, which is try to use libp2p stacks to build a simple p2p ftp. And I didn't remove prefix on `node.host.Connect`. 

Actually, my original code is do dht.New before connect. If you are free, feel free to look at https://github.com/leslie-wang/libp2p-ftp/blob/master/node/node.go#L61, which starts node as ftp server, and https://github.com/leslie-wang/libp2p-ftp/blob/master/node/node.go#L41, which connect to node as client. 

There are plenty of errors about `Error unmarshaling data: stream reset` and `protocol mux failed: stream reset (took 111.711442ms)`. Not sure if it can give any hints.

**Comment by upperwal** [comment]
@leslie-wang ok. Got it. Your code looks good. Can you tell me what do you expect and what is happening right now in the code?

> Peer B is also behind NAT, and connect to same sets of bootstrapNodes, then try to find the Peer A using its peer ID as below. Seems like it fail.

Specifically, what does fail mean in your case?

**Comment by bCoder778** [comment]
What's the difference between 'dht.FindProviders'  and 'routingDiscovery.FindPeers'

**Comment by Stebalien** [comment]
@bCoder778 please ask on [discuss.libp2p.io](https://discuss.libp2p.io).
