### ISSUE TITLE
Nat traversal port selection

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p#383]
I have an ipfs node that is behind a NAT, but I have port forwarding set up.
Despite this, my peer does not advertise any reachable address (it doesn't know about the port forwarding).

I *could* manually add the right address to my advertised addresses, but forcing users to do that is kindof obnoxious UX.

We *should* probably have nodes discover their gateways, attach their listen ports to it, and then ask some nat service to try dialing us through it. If that succeeds, then we should add it to our list of known good addresses.

**Comment by Stebalien** [comment]
I believe the issue here is that the node is running on freebsd, which doesn't support reuseport. Therefore, it's using random ports when dialing. Unfortunately, that means that we're *advertising* these random ports.

But yeah, we should do as @whyrusleeping says: figure out which external addresses are reasonable and ask some node to try dialing them. Unfortunately, the current libp2p construction makes this a bit tricky (connection deduplication).

**Comment by Stebalien** [comment]
NATs may also be messing with these ports.

**Comment by Stebalien** [comment]
So, my attempted fix was wrong. We already expose the addresses on `Host.Addrs`.

There are two issues here:

1. The nat we were testing on was broken. The router reported its internal address as its external address. Fixing this will require some work.
2. We don't *re*-announce addresses to the network. That is, we gossip them when connecting to our DHT neighbors but we don't then send these neighbors updated addresses.

**Comment by marten-seemann** [comment]
This should (partially) be solved by AutoNAT, and more elegantly by [AutoNAT v2](https://github.com/libp2p/specs/issues/503).
