### ISSUE TITLE
I need help o(╥﹏╥)o

### ISSUE THREAD

**Issue by Ice-Storm** [libp2p/go-libp2p#406]
I don't know how to combine with libp2p-kad-dht.  confused me for days. how to find a peer? Can you give me a demo?
o(╥﹏╥)o

**Comment by upperwal** [comment]
@Ice-Storm Have a look at [libp2p/go-libp2p-examples](https://github.com/libp2p/go-libp2p-examples) repo. Some example that support dht are under review look at [chat-with-rendezvous](https://github.com/libp2p/go-libp2p-examples/pull/6) and [chat-with-tor](https://github.com/libp2p/go-libp2p-examples/pull/1). They both support kad-dht and peer discovery.

**Comment by Ice-Storm** [comment]
@upperwal This example help me a lot, But i still confused that how to implement 'root' node. 
This example connect some node by bootstrap, but bootstrap node how to init ?

**Comment by upperwal** [comment]
@Ice-Storm Creating a new bootstrapping node is as simple as starting a new node with **DHT support** [atleast for now]. @Stebalien can you please confirm this.

@florianlenz is working on a bootstrap module plus the community is also working on a new [rendezvous protocol](https://github.com/libp2p/specs/pull/56) for the same.

Maybe we can have a sample code in examples to start a bootstrap node.

**Comment by Ice-Storm** [comment]
@upperwal thank you.  I am trying it out.

**Comment by Ice-Storm** [comment]
@upperwal Sorry to bother you. I just had a quick question. When I run the chat example, I find that the message does not broadcast when multiple terminals are started. like this 
![wechatimg322](https://user-images.githubusercontent.com/10904646/46596372-ed899e80-cb0e-11e8-85a3-4ff28a6cd23d.jpeg)
Could you give some reason? all connect use same `net.Stream` ?
Thank you.

**Comment by upperwal** [comment]
> I find that the message does not broadcast when multiple terminals are started

Yeah, it won't broadcast and your message might be going to either one of the peer/terminal at a time. 

This is happening because each peer opens a new stream for chat and starts a new goroutine to read from ```stdin``` and this is the problem. One stdin stream and multiple goroutines to read it (one for each connected peer). Only one of the goroutine will succeed and send the messege to one peer. 

A better chat implantation would be to use a pubsub model where peers can subscribe to chat rooms and everyone in that room will receive the message.

Another way would be to start one goroutine which read stdin and copy the message to all connected peers stream.

**Comment by Ice-Storm** [comment]
Thank you. I'm study that how to constructor  p2p network and related knowledge. you replay help me a lot. i hope to make more contributions to this project.
