### ISSUE TITLE
What does host.NewStream() really do in TCP level in details ?

### ISSUE THREAD

**Issue by woniuxu** [libp2p/go-libp2p#413]
Hi all,

I run go-libp2p-examples/echo program on one terminal like: ./echo -l 1200 and the other:  ./echo -l 1201 -d /ip4/10.127.24.115/tcp/1200/ipfs/QmcWjovzdKKgY4gPeuSkuDwHM6V3J4bdtGez3AmogLwkrS.

And use wireshark to see what happened to tcp packets in the execution of "opening stream". The capture is like the first three lines indicate tcp handshake and at line 58 the "Hello World" message are really sent out. So I wonder why it takes dozens of tcp packets before the "Hello World" message is sent out ? Or what does host.NewStream() really do to make the stream ready for writting data? Thanks.
![image](https://user-images.githubusercontent.com/1635703/45208525-5afea100-b2bd-11e8-9f8b-c4b422c8418e.png)
![image](https://user-images.githubusercontent.com/1635703/45208605-91d4b700-b2bd-11e8-8a7e-4d997a8ac299.png)

**Comment by Stebalien** [comment]
1. We negotiate the security transport. For this example, we negotiate the "plaintext" (insecure) security transport by default (which you should never do in practice).
2. We negotiate a stream *multiplexer*. That is, once we open a single TCP connection, we figure out how to multiplex multiple "streams" over the same connection.
3. We run an "identify" protocol (although we may be running this in parallel with everything else). This allows both sides to tell eachother about themselves.
4. That example will open a new stream.
5. It'll negotiate the `/echo/1.0.0` protocol.
5. Finally, it'll *use* the echo protocol.

You're right, we're sending *way* too may packets. We need to:

1. Improve the negotiation protocol. It's currently rather chatty.
2. Switch to QUIC instead of TCP. It has built-in encryption, stream multiplexing, and the ability to send basic "identifying" information so it should do steps 1-3 all in 1.
3. Buffer better. We currently send *way* too many packets.
