### ISSUE TITLE
[Question] libp2p build for mobile

### ISSUE THREAD

**Issue by upperwal** [libp2p/go-libp2p#431]
Recently, I was able to build libp2p for Android using gomobile. Surprisingly, it worked out of the box [never expected that] with minor issues and I was able to create a p2p chat app with peer discovery using DHT entirely on Android. 💥 🌟 🎉 

For this, I had to create an interface (something similar to Ethereum mobile but obviously less complicated and small) to be used in gomobile. Right now it gives you access to Host, Connection and Stream API [minimalistic setup] which an Android developer can use in his app.

I know support for Mobile devices is not a priority for the community but there could be endless possibilities of p2p use cases for edge and mobile devices from as simple as a chat platform to p2p marketplace on mobile totally decentralised. [yes, I am working on a similar idea]

I would like to reach out to people who can relate to this and community members for their input and ideas on the same. I am more than happy to contribute.

**Comment by Stebalien** [comment]
> I know support for Mobile devices is not a priority for the community but there could be endless possibilities of p2p use cases for edge and mobile devices from as simple as a chat platform to p2p marketplace on mobile totally decentralised

Actually, we'd love this. We just need to reduce memory usage, background bandwidth, and connection count first.

You'd be interested in the libp2p daemon endevor (https://github.com/libp2p/go-libp2p-daemon) which will (eventually) allow multiple applications to share the same daemon.

You should also chat with the textile and peergos groups (cc @andrewxhill @ianopolous).

**Comment by upperwal** [comment]
Hey @Stebalien. Thanks a lot for your comments. I agree that some optimisations are required to make libp2p mobile ready. I am planning to look at them one by one to check for scalability and cost of operations for my use case.

Closely following libp2p daemon project and I think it is a great initiative. Let me know if I can be of any help and again thanks for the intro, will surely get in touch with them.

**Comment by JackBekket** [comment]
Hi!

Can you kindly provide me a link for this project?

**Comment by JackBekket** [comment]
Look's like that is exactly what I was looking for my project

A few notes, which I have discovered during my work on this idea:
1. we actually could use Rendez-vous point discovery for 'secret chats' feature. And what I think is more important - that will be fully decentralized secret chats.  
I don't think that it could be applied to general messaging (cause in this case we wouldn't able to chat with offline users and we can't keep messages history), but for secret chats it is actually a good feature.
Meanwhile, we, of course, could have use Matrix ecosystem for usual, general messaging

2. If you think about possible pitfalls like battery consumption, memory consumption, and background bandwidth - I believe that we can use a hybrid network environment model. 
I mean - what if there are some bearing nodes - PC, which have a connection to a power line, and host local chat in the location - then mobile device should only connect to this PC instead of having multiple connections to every mobile device at the area

3. About possible business/use cases, that I've found so far:

- Customer Acquisition and any solution related to geotargeting - in this particular case we can use mdns discovery - it gives us info that user device is actually located in the area of wi-fi network of some coffee shop for example - which give coffeeshop owner possibility to interact with his customers locally.- so it gives us mechanics of coupons, check-ins and so on

- Local datings (brave style) - imagine that you want to meet with someone, inside of your location - nether it could be a conference or just Irish pub
Once again, you can use mdns for locate peers nearby in the network and start to communicate with it. Also, we could exchange users 'topics' in such local environment and match users with similar interests (and it is actually will work with more accuracy than any GPS based location)

**Comment by JackBekket** [comment]
So, I would interesting in such project on Android, especially if it works with mdns peer discovery

**Comment by jacobheun** [comment]
While the libp2p core team is not directly working on mobile efforts there are several community teams working on various mobile versions. For example, Textile has some clients for IPFS for both android and ios: 
- https://github.com/textileio/android-ipfs-lite
-  https://github.com/textileio/ios-ipfs-lite.

**Comment by mrbluecoat** [comment]
@upperwal interested in porting [hyprspace](https://github.com/hyprspace/hyprspace) to Android? https://github.com/hyprspace/hyprspace/discussions/4
