### ISSUE TITLE
Somehow combine go-libp2p-crypto and go-libp2p-peer

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#484]
Peer IDs and keys are closely tied together. Unfortunately, they currently live in two separate packages. My current thinking is either:

1. Move crypto into peer (and make a new crypto that depends on peer and re-exports).
2. Combine into go-libp2p-identity and create a new peer *and* crypto facade.

My motivation is fixing https://github.com/libp2p/specs/issues/111. We *need* to be bale to deterministically derive peer IDs from keys. That means keys nee to remember their multihash. However, that's a peer-ID concern which doesn't really fit in the current go-libp2p-crypto package.

@raulk this is related to your monorepo suggestion and, IMO, a good start. We could also combine these packages with a few others if we have some other "core" concepts.

Note: fixing https://github.com/libp2p/specs/issues/111 is a rather high priority so I don't want to block it on reworking all of our dependencies.

**Comment by vyzo** [comment]
I am in favour of having a meta-package for this; crypto is useful outside the concept of peer.

**Comment by raulk** [comment]
@Stebalien agree it'd be good start to consolidating repos. I don't suppose we'd entertain the idea of moving both peer and crypto to somewhere more central, though? 

go-libp2p wouldn't be that place, because clients can instantiate libp2p without importing go-libp2p (ironically), i.e. if they're using BlankHost.

In our current layout, that central place could be go-libp2p-host. You really cannot have libp2p without importing `Host`; so it's an unconditional dependency.

```
go-libp2p-host
  |___ id
  |___ crypto
  |___ ...
```

If somebody _really_ wants to use `PeerID` outside of libp2p (?), or use our crypto constructs, they can still do so by importing these packages directly.

**Comment by Stebalien** [comment]
I'm going to take a stab at making a `go-libp2p-interfaces` package.

**Comment by emad-elsaid** [comment]
Is there any changes to the implementation or a decision made about this issue?

**Comment by Stebalien** [comment]
All core interface libraries have been merged into `go-libp2p-core`.
