### ISSUE TITLE
Option to force autorelay without probing autonat

### ISSUE THREAD

**Issue by vyzo** [libp2p/go-libp2p#518]
This has come up in conversations around filecoin UX in the case of known bad NAT.
The concern is that the user might get frustrated with the delay in establishing autonat undialability and conclude that it doesn't work.
The consensus solution is to have an option to force relay without probing autonat when using autorelay,
This would also be beneficial for ipfs, where a similar situation might arise.

Action:
- add a libp2p constructor option, that works in conjunction with autorelay, and disables autonat probing.

cc @ZenGround0 @Stebalien

**Comment by Stebalien** [comment]
Is this theoretically necessary? Unless I'm missing something, that delay exists because we don't have any event systems in-place. That is, we should be able to detect NAT issues pretty fast.

We may also be able to speed things up by restructuring our NAT modules a bit. Instead of having the AutoNAT detection module be independent of the NAT hole punching module, we could have a parent "nat" service that works with both.

---

We could have some feature that turns on AutoRelay if we can't determine our NAT status within some very short timeout and then immediately turns it off. However,

1. We'd likely want some way to migrate connections. Otherwise, our poor relays are going to be swamped.
2. We need to be able to propagate address changes reliably (IIRC, this will require much of the network to update).

---

>  This would also be beneficial for ipfs, where a similar situation might arise.

Anything that involves user intervention tends cause more trouble than it saves. IMO, options are useful for:

1. Servers, datacenters, and special cases. In these cases, we can expect users to tweak their nodes.
2. Experimental features. Power users can test them first but we can turn them on for everyone else later.

Unfortunately, *this* option is something that's primarily useful for home users. If we provide it, I expect tutorials to pop up telling *all* users to enable it (which will cause some pretty large issues with our network).

**Comment by magik6k** [comment]
This option would also be useful for nodes running in web browsers - https://github.com/ipfs/go-ipfs/pull/5878 (admittedly it's a rather extreme edge case).

**Comment by vyzo** [comment]
> Is this theoretically necessary?

I don't think so, it's just a matter of UX. Filecoin wants it though.

> Unless I'm missing something, that delay exists because we don't have any event systems in-place. That is, we should be able to detect NAT issues pretty fast.

Correct, but there is still one delay we can't avoid: the dial back error reporting delay, currently sitting at 42s. Perhaps we should reduce this delay, but we can't eliminate it altogether.

> We could have some feature that turns on AutoRelay if we can't determine our NAT status within some very short timeout and then immediately turns it off.

Or we can be more aggressive and decide to advertise relay addresses while the NAT status is unknown (but without removing the public address from the advertised list).

> We need to be able to propagate address changes reliably (IIRC, this will require much of the network to update).

that's not an issue for filecoin, as the network hasn't launched yet.

**Comment by vyzo** [comment]
> Really, I think they want this for demos.

probably :)

> Is that because the remote side will wait 42 seconds before it gives up?

yes, that's the dialback timeout.

>> Or we can be more aggressive and decide to advertise relay addresses while the NAT status is unknown (but without removing the public address from the advertised list).
>
> Pending the dialer prioritization work, this sounds like a reasonable default.
> ...
> I think it's fair to announce both a relay and a non-relay address until we get the NAT status back.

I really want to put this behaviour behind a flag though, as the current dialer will start dialing relays concurrently with the public address.

**Comment by Stebalien** [comment]
> I really want to put this behaviour behind a flag though, as the current dialer will start dialing relays concurrently with the public address.

Totally! This also brings up the whole "interactive ipfs init" issue (https://github.com/ipfs/go-ipfs/issues/4877). Ideally, laptop users would enable this and server users would disable it.

---

Ok, I just wanted to make sure we were thinking through this instead of building a foot gun.

**Comment by mgoelzer** [comment]
I'd like to revisit whether this issue is truly a P1 for Filecoin.  There's been no discussion since February 2019.  I'm defining [Filecoin P0's and P1's](https://docs.google.com/spreadsheets/d/1afPkJ3ZzKHXheUHWat9mNWnuJADdr7EtehBXhzrtttA/edit#gid=1213179753) as things that basically must be completed by December 11, 2019, their testnet launch date.

@ZenGround0 Can you re-read the history here and let me know if you feel this whole thing is still a Filecoin P1 (meaning that it may block the testnet or mainnet launch dates).  It's totally fine if the answer is yes, but the person who will work on this is the same person who is trying to eliminate much of the need for relays by immediately upgrading relay connections to direct p2p connections.  So, telling him that this flag is a Filecoin launch blocker will probably pause work on other work which is superior for everyone in the long run.  That may be the right decision, but I'd like to make sure we're not making it based on stale data.

@Stebalien / @vyzo Could you also review this issue and comment on whether the flag solution is still our recommended solution?  We have a lot more data now about relays and their limitations than we did in Jan/Feb.  Assuming Wyatt says that the long delay is still a P1 for FC, do we still believe this flag is the best solution to recommend to them?

**Comment by marten-seemann** [comment]
We have a `ForceReachabilityPrivate` option. I believe that resolves this issue.
