### ISSUE TITLE
Moving DHT into libp2p from ipfs

### ISSUE THREAD

**Issue by geoah** [libp2p/go-libp2p#56]
The DHT package in IPFS seems to be pretty self sufficient so I was wondering if there is any plan to move it in `go-libp2p`.

Disclaimer: I'm pretty new to `go-ipfs`/`go-libp2p` and I'm still trying to wrap my head around `gx` which is my main issue with DHT being in IPFS. But in any case, DHT would be an amazing addition for `libp2p`. :D

ps. `libp2p` is the most amazing piece of spec and implementation for anything p2p I have had the pleasure of gazing upon and I really want to thank you for it.

**Comment by jbenet** [comment]
> The DHT package in IPFS seems to be pretty self sufficient so I was wondering if there is any plan to move it in go-libp2p.

yes.

> gx

let us know if anything could make the readme github.com/whyrusleeping/gx more understandable at first pass. it assumes some amount of ipfs knowledge or deep git knowledge. (hashes, refs, etc)

> ps. `libp2p` is the most amazing piece of spec and implementation for anything p2p I have had the pleasure of gazing upon and I really want to thank you for it.

@geoah thanks very much for the kind words :)  we have a long way to go until it's all super nice, but it's getting there :)

**Comment by whyrusleeping** [comment]
@geoah feel free to ask any noob questions you need to about libp2p and ipfs or gx stuff. If youre needing more immediate answers, definitely join us on freenode irc in #ipfs, theres a bunch of there that can help out :)

**Comment by jdfweb** [comment]
@jbenet thanks for the help!

**Comment by mildred** [comment]
Is anyone working on this ?

**Comment by geoah** [comment]
Got some spare time so I tried tackling this; but I run into some issues.
But I had to create three forks to make this actually work which seems a bit over the top.

a. [`ipfs/go-ipfs` fork](https://github.com/geoah/go-ipfs/tree/chore/remove-dht) removes dht and rewrites packages to point to libp2p dht (still need to check tests)
b. [`libp2p/go-libp2p` fork](https://github.com/geoah/go-libp2p/tree/chore/add-dht-from-ipfs) adds dht and undoes gx rewrite (tests pass)
c. [`jbenet/go-peerstream` fork](https://github.com/geoah/go-peerstream/tree/chore/remove-vendoring) removes vendored packages and undoes godeps rewrite.

My Issues with this.

1. Even though `go-libp2p-transport` seems to import `github.com/anacrolix/utp`, this is not the correct repo to import. You actually need `/ipfs/QmPSR1zYgWRmTSt6nTGXdeeUhWkq9AdvK4sva4Y2H5daPi/utp` which I have no idea where to find outside of ipfs.
I had to download and replace `github.com/anacrolix` the the ipfs one to make dht work.

2. `github.com/jbenet/go-peerstream` is using `Godeps/_workspace` and creates a couple of wrong-type errors. Un-doind vendoiring on this repo fixes thd dht errors.

3. I had to `gx-go rewind --undo` my `go-ipfs` repo to make any of this work.

It feels like I'm doing something wrong with vendoring... How do you all deal with it? Use `gx` for everything and rewrite before commiting or something different?

I haven't made any pull requests as I have the feeling that there is a simpler way to do this that I'm missing. I can try again if someone points me to the right direction! :)

Thank you all.

**Comment by geoah** [comment]
The `go-peerstream` issue also relates to #66

**Comment by shazow** [comment]
We definitely need to remove the hardwired third-party tooling imports. Assuming everything else builds, I would suggest making PRs with your forks that achieve this, I did this in https://github.com/whyrusleeping/libp2p-examples/pull/4 and it was merged.

The state of things as they are now has discouraged me from taking a day to work on this stuff on more than one occasion, we're probably missing out on tons of collective effort because of it.

**Comment by whyrusleeping** [comment]
@geoah I think it would be best if the dht code went into a separate repo, like `libp2p/go-libp2p-dht` or `libp2p/go-libp2p-kad-dht`. That would make it a lot more accessible I think.

When working on libp2p, i generally do a `gx-go rewrite` to make sure the dependencies i'm working with are the correct ones, do my changes, run the tests, etc, and then `gx-go rewrite --undo` before comitting.

You can do most (minus the peerstream thing, which i have changed locally) of the work without the gx dependencies, but many of the packages we import change underneath us and make things pretty difficult to work around. as an example, I don't generally feel like debugging an issue in yamux while fixing an unrelated bug in swarm.

On go-peerstream, we need to redo this PR: https://github.com/jbenet/go-peerstream/pull/22 in order to get the deps out of Godeps and into gx.

**Comment by geoah** [comment]
@whyrusleeping if you can create a new repo for the dht under `libp2p` I can make a PR to it and then push that to `/ipfs/` for gx to work before making a new PR for `go-ipfs`.

Unless you prefer to leave the splitting to one of you :)

**Comment by geoah** [comment]
I got a clean split at [geoah/go-libp2p-kad-dht](https://github.com/geoah/go-libp2p-kad-dht) working; or at least [tests seem to passing](https://travis-ci.org/geoah/go-libp2p-kad-dht).

**Comment by whyrusleeping** [comment]
@geoah alright, made libp2p/go-libp2p-kad-dht, go ahead and PR :)

**Comment by geoah** [comment]
@whyrusleeping sorry to bother you again, but can you please commit a README or something on the repo?! :D Github doesn't allow me to fork or create PRs empty repos hehe..

**Comment by dignifiedquire** [comment]
@whyrusleeping @geoah readme added

**Comment by geoah** [comment]
Closing this in favour of libp2p/go-libp2p-kad-dht/pull/1
