### ISSUE TITLE
the PeerInfo got from FindPeers has EMPTY Addrs.

### ISSUE THREAD

**Issue by LiMoMoMo** [libp2p/go-libp2p#567]
bootstrap_node: A
node: B
node: C
B and C all connected to bootstrap_node A. 
B called `discovery.Advertise(somestring)`, then C call `routingDiscovery.FindPeers(somestring)`, it can get PeerInfo with B's ID and Addrs.
But after maybe 10 minutes, C call `routingDiscovery.FindPeers(somestring)` only get PeerInfo with B's ID but has no Addrs, the node B is online when C called`routingDiscovery.FindPeers(somestring)`.

After reboot B, C can get Addrs from `routingDiscovery.FindPeers(somestring)` immediatly.

**Comment by upperwal** [comment]
@LiMoMoMo I think this issue is also related to [a race condition](https://github.com/libp2p/go-libp2p-examples/issues/42#issuecomment-473659241).

**Comment by LiMoMoMo** [comment]
> @LiMoMoMo I think this issue is also related to [a race condition](https://github.com/libp2p/go-libp2p-examples/issues/42#issuecomment-473659241).

thanks😄

**Comment by Stebalien** [comment]
go-libp2p nodes forget peer _addresses_ 10 minutes after closing the connection as it assumes that peers may move around. That's why you get the peer ID but not the addresses.

However... It _sounds_ like peer A remains connected to peers B and C. If that's the case, peer A _shouldn't_ forget these addresses. Is that so?

**Comment by Stebalien** [comment]
Ah, I think I know. The issue is that peer C is _caching_ the provider record. Because C is not connected to B, C forgets B's addresses after 10 minutes (even though it remembers that B is providing the content.

Note: When you later try to _dial_ this peer, you should automatically try to find the peer in the network (even if you don't know the peer's addresses up-front).
