### ISSUE TITLE
Dial backoff

### ISSUE THREAD

**Issue by JackBekket** [libp2p/go-libp2p#643]
Hi!

I'm trying to run libp2p example (chat with mDNS) on a different devices in one local network (wi-fi)

When I try to connect two linux devices it's work well, but if I try to connect between linux and windows it's failing.

I've tried connect from two different windows machine to linux, one of them seem's like don't even find peers, second one finds linux peer, but failed with connection to it

It says `stream open failed dial backoff`

Can it be OS related or network related or firewall related?
Does anyone tried to run libp2p applications on windows?

**Comment by Stebalien** [comment]
"dial backoff" usually means it tried to connect but failed, so it decided to stop trying. It's likely firewall related. That is, your node likely _tried_ to connect once (likely because it saw an mDNS advertisement), failed, set a "backoff", then _you_ tried to connect and ran into this backoff.

Do you have an inbound firewall configured?

**Comment by JackBekket** [comment]
I've tried to set firewall off on windows machines, but it doesn't help yet

https://github.com/libp2p/go-libp2p-examples/issues/62

**Comment by JackBekket** [comment]
@Stebalien It's look's like `context background` working weird on windows devices, because it announce localhost in advertisment instead of real address

**Comment by Stebalien** [comment]
Are you enabling AutoRelay by any chance? Could be related to https://github.com/libp2p/go-libp2p/pull/667.

**Comment by Stebalien** [comment]
(closing as this appears to be unrelated to dial backoff)
