### ISSUE TITLE
NAT traversal: Implement support for simultaneous open in mulstistream

### ISSUE THREAD

**Issue by vyzo** [libp2p/go-libp2p#712]
Tracking issue for the implementation of https://github.com/libp2p/specs/pull/196

PRs:
- [ ] https://github.com/multiformats/go-multistream/pull/42
- [ ] https://github.com/libp2p/go-libp2p-core/pull/53
- [ ] https://github.com/libp2p/go-conn-security-multistream/pull/14
- [ ] https://github.com/libp2p/go-libp2p-transport-upgrader/pull/25
- [ ] https://github.com/libp2p/go-libp2p/pull/711

**Comment by marten-seemann** [comment]
Continuing the discussion started in https://github.com/libp2p/go-libp2p-tls/pull/38#issuecomment-558587045 here.

@vyzo, it seems like our suggested interface changes for solving simultaneous open in ms-1.0 are very similar, but slightly different: I was suggesting to change the `SecureTransport.SecureOutbound` function, whereas in https://github.com/libp2p/go-conn-security-multistream/pull/14/ you're changing the `SecureMuxer.SecureOutbound` function.

If I understand things correctly, changing `SecureMuxer.SecureOutbound` only works if you negotiate the roles *before* actually starting the cryptographic handshake. So it's a perfectly fine thing to do for multistream-1.0, but unfortunately will not work with multiselect-2.0, since we there discover *during* the handshake that a simultaneous open occurred.

**Comment by vyzo** [comment]
Yeah, that was required for `multiselect/1.1` because we negotiate the role.
We'll have to figure out something slightly different for `ms/2.0`.

**Comment by marten-seemann** [comment]
It would be nice if we only had to change one of the interfaces to make it work for both ms-1.1 and ms-2.0 though. Arguably, dealing with simultaneous open belongs more into the transport than in the muxer, so I was wondering if libp2p/specs#196 could also be implemented that way.

**Comment by aarshkshah1992** [comment]
This is now being tracked as part of https://github.com/libp2p/go-libp2p/issues/712.
