### ISSUE TITLE
Gossipsub messages not reaching all subscribers to that topic

### ISSUE THREAD

**Issue by mgoelzer** [libp2p/go-libp2p#721]
A go-libp2p user reported this to me yesterday, and I didn't see an open issue already.  Title pretty much includes all the information that we have at this point:  some peers subscribed to topic `T` appear not to be receiving all `T` messages, and we don't know why.  Next step would be to get the user code and try to repro it ourselves.

**Comment by vyzo** [comment]
also, the user need to look at the logs -- oftentimes there are dropped messages because of full queues, regardless of the protocol.

**Comment by aschmahmann** [comment]
@vyzo the full queues are just the most common way a test will show dropped messages, network issues in a connected network could also cause dropped messages. Fundamentally the protocol has nothing built in for reliability or persistence aside from the network topologies allowing the same data to flow down multiple paths, otherwise we'd end up doing things like rebroadcasting or notifying peers about dropped messages.

If a large number of users want a reliable pubsub then either we should explain why we're not targeting that use case or we should make sure to have an alternative available for them.

**Comment by mgoelzer** [comment]
> If a large number of users want
I don't have the data right now to suggest this.

@aschmahmann @vyzo Thanks for your quick reply on this.  I'm inclined to close this issue for now until we better understand the user need/expectation here.
