### ISSUE TITLE
Use raw multihashes for providers

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#755]
Currently, we're using CIDs. However, multiple CIDs can map to the same block (v1, v0, different codecs). Due to the base32 CID migration effort, we'll need to switch over the routing system to use raw multihashes.

Note: Given that raw multihashes are still valid V0 CIDs, old servers will continue to work.

Proposed changes:

1. Change the routing interfaces to take multihashes.
2. In `handleAddProvider`, just use strings/[]byte; don't parse anything (although we can assert that the length < 100 bytes (or something like that). We could also just use mutlihashes but then we'd need to change the multihash library to handle unknown multihash codes (which we may want to do anyways?).

@kevina is working on this from the go-ipfs side but he'll need someone on the libp2p side to implement these content-routing changes. Any takers?

**Comment by aschmahmann** [comment]
@Stebalien any chance we can do an easier version of this that doesn't require interface changes so we can ship this soon?

Proposal: Leave the interfaces the same, but send multihashes over the wire. Since CIDv0 is a multihash none of those records should change, CIDv1 records will change (so newer and older clients will have not be able to find each others' CIDv1 data).

Is the CIDv1 record incompatibility a problem? If so then the only options I can think of right now are for clients to do multiple queries for a while before we deprecate the publishing CIDv1s, or to rely on a dht version bump to force the deprecation.

**Comment by Stebalien** [comment]
> @Stebalien any chance we can do an easier version of this that doesn't require interface changes so we can ship this soon?
>
> Proposal: Leave the interfaces the same, but send multihashes over the wire. Since CIDv0 is a multihash none of those records should change, CIDv1 records will change (so newer and older clients will have not be able to find each others' CIDv1 data).


Yes. Let's do it.

> Is the CIDv1 record incompatibility a problem? If so then the only options I can think of right now are for clients to do multiple queries for a while before we deprecate the publishing CIDv1s, or to rely on a dht version bump to force the deprecation.

Hm. It may be a bit annoying for rendezvous (e.g., pubsub), but I think we'll be fine with a clean break.

**Comment by jacobheun** [comment]
Closing this as multihashes are now being used.
