### ISSUE TITLE
Implement (finish) circuit switching relay

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p#82]
circuit switching is a very basic form of relaying that we already have some code in place for in `p2p/protocol/relay`. The code isnt currently functional and needs some attention.

Implementing circuit switching means that we can provide nearly 100% connectivity to users. Anyone who can connect to a public relay node should be able to communicate with any other user in the network (who can also connect to a public relay).

Tasks:
- [ ] finish and test code in `p2p/protocol/relay`
- [ ] determine how this code will be used
  - `Host` addon
  - if X dials fail, try using a relay?
  - Try using a relay and dialing normally at the same time, drop relay if normal connection succeeds?
- [ ] add config option to set your node as a relay
- [ ] config option for rate limiting relayed connections. (bandwidth of each, and total count)
- [ ](infra) set all gateway nodes as open relays

**Comment by lgierth** [comment]
cc @diasdavid @victorbjelkholm this is relevant to you two because of js-libp2p-relay.

I started working on relay in go-ipfs as part of the "browser accesses go-ipfs sprint" (ipfs/pm#130).

So far I think the cleanest solution is to make the relay service a transport, so that we get end-to-end encryption -- the existing but unused relay code makes no attempt at that. It might at first feel weird that a swarm protocol is at the same time a transport, but this kind of stack hopping is what you sign up for when building overlay networks. It'll be something like: the RelayService calls `Host.NewStream()` and `Host.SetStreamHandler()`, and the Host calls `RelayService.AddRelayPeer()`

In the end I think this solution is the simplest in that it doesn't have to touch any existing libp2p interfaces. It will also fit in nicely with any future things like transport capabilities and connection estimators.

- [ ] `/relay` multiaddr (`/relay-exp` for now)
  - Just a PeerID is enough, RelayService picks a suitable peer for relaying
  - Can be explicit though: `/ip4/1.2.3.4/tcp/4737/ipfs/Qmfoo/relay/Qmbar`
  - Nice side-effect for free: multihop: `/relay/Qmfoo/relay/Qmbar/relay/Qmbaz`
- [ ] RelayService
  - Implements `go-libp2p-net.StreamHandler` and `go-libp2p-transport.Transport`
- [ ] Config option for relay hosts
  - Probably a static list for now?

**Comment by lgierth** [comment]
The spec is in libp2p/specs, the `/p2p-circuit` multiaddr has been added to the protocol table, and @dryajov has made great progress on js-libp2p-circuit.


:ship::ship::ship:

**Comment by diasdavid** [comment]
The spec was revisited and released as 0.1.0 - https://github.com/libp2p/specs/tree/master/relay
